#!/usr/bin/env python3

import time
import json
import os
import notify2
import mosquitto

notify2.init("smssync")
uri = os.path.abspath(os.path.curdir) + "/harbour-smssync-mini.png"

###

def msg(payload):
    n = notify2.Notification(
        "{0} {1}".format(
            ">" if payload.get('dir') == 'in' else '<',
            payload.get('from')
        ),
        "\n" + payload.get('content'),
        uri
    )

    n.set_timeout(20000)
    n.show ()


###

def on_connect(*rc):
    pass

def on_message(obj, userdata, msg):
    # smssync/jollahq/notify {"content": "Grec","dir": "in","from": "+336XXXXXXXXXX","id": "","type": "msg"}
    payload = json.loads(msg.payload.decode('utf8'))
    #print(msg.topic + "," + msg.payload.decode('utf8') + "," + payload.get('type'))

    if payload.get('type') in globals():
        (globals()[payload.get('type')])(payload)


if __name__ == '__main__':
    client = mosquitto.Mosquitto("desktop")

    client.on_message = on_message
    client.on_connect = on_connect


    while True:
        try:
            client.connect("localhost", 1883, 60, True)
            client.subscribe("smssync/#", qos=2)

            while client.loop() == 0:
                pass

        except Exception as e:
            print(e)

        time.sleep(.5)

