#!/usr/bin/env python3

import sys
import time
import json
import os
import notify2
import mosquitto

notify2.init("smssync")
uri = os.path.abspath(os.path.curdir) + "/harbour-smssync-mini.png"

###

def msg(payload):
    n = notify2.Notification(
        "{0}: {1} ({2})".format(
            "received from" if payload.get('dir') == 'in' else 'sent to',
            payload.get('contact', {}).get('name'),
            payload.get('contact', {}).get('phoneNumber')
        ),
        "\n" + payload.get('content'),
        uri
    )

    n.set_timeout(20000)
    n.show ()


###

def on_connect(*rc):
    pass

def on_message(obj, userdata, msg):
    # smssync/jollahq/notify {"content": "Grec","dir": "in","from": "+336XXXXXXXXXX","id": "","type": "msg"}
    payload = json.loads(msg.payload.decode('utf8'))
    #print(msg.topic + "," + msg.payload.decode('utf8') + "," + payload.get('type'))

    if payload.get('type') in globals():
        (globals()[payload.get('type')])(payload)


if __name__ == '__main__':
    (server, port) = ("localhost", 1883)
    if len(sys.argv) > 1:
        args = sys.argv[1].split(':')
        server = args[0]

        if len(args) > 1:
            port = int(args[1])

    client = mosquitto.Mosquitto("desktop")

    client.on_message = on_message
    client.on_connect = on_connect


    while True:
        try:
            client.connect(server, port, 60, True)
            client.subscribe("smssync/#", qos=2)

            while client.loop() == 0:
                pass

        except Exception as e:
            print(e)

        time.sleep(.5)

